### ISSUE TITLE
Provide a wiki how to update the new manual

### ISSUE THREAD

**Issue by iloveeclipse** [spotbugs/spotbugs.github.io#18]
I'm trying to understand how the current code here maps to the state I see at http://spotbugs.readthedocs.io/en/latest/. 
I honestly have no clue. 

We should provide a simple how to about fixing and uploading the docs.

**Comment by KengoTODA** [comment]
Its code exists in `docs` directory in `spotbugs` project.
How to build is described in [`docs/README.md`](https://github.com/spotbugs/spotbugs/blob/master/docs/README.md).

About .rst format, please refer [official document](http://docutils.sourceforge.net/rst.html).

Are they helpful enough for you?

**Comment by iloveeclipse** [comment]
A-ha. It means, all the manual.xml ect files in the root of the https://github.com/spotbugs/spotbugs.github.io repo are obsoleted?
We should remove all of them.

After reading https://github.com/spotbugs/spotbugs/blob/master/docs/README.md I still have no clue how the result is deployed to https://spotbugs.readthedocs.io/en/latest/bugDescriptions.html and what is needed for that.

I would prefer we would have a README.md in the root of *this* repository and explain all the needed points here or at least link to the another readme.

**Comment by KengoTODA** [comment]
>  we would have a README.md in the root of this repository

OK I will propose PR.
