### ISSUE TITLE
Add quickstart to the homepage

### ISSUE THREAD

**Issue by koppor** [spotbugs/spotbugs.github.io#23]
When I am using gradle, the homepage does not provide a hint to start the tool. There is no task `spotBugs`. When including the gradle pulgin, there is `findBugsMain` (which currently does not work - see https://github.com/spotbugs/spotbugs/issues/250).

- [ ] Could you add somewhere that one has to execute `findBugsMain`? 
- [ ] Could you add an example output?
- [ ] Could you add information how to apply the plugin [fb-contrib](http://fb-contrib.sourceforge.net/). `fb` is not the same as `spotbugs` and so I wonder how they are compatible and how I can use these rules within a gradle setting.

**Comment by JuditKnoll** [comment]
The official documentation is referenced on the website.
See the relevant part of the official documentation: https://spotbugs.readthedocs.io/en/latest/gradle.html
You can also find usage example in the readme of the spotbugs-gradle-plugin: https://github.com/spotbugs/spotbugs-gradle-plugin?tab=readme-ov-file#usage
