### ISSUE TITLE
Is it possible to exclude bugs file using spotBugs like findBugs ?

### ISSUE THREAD

**Issue by ASNOUN** [spotbugs/spotbugs.github.io#35]
Hi,

Environment
Spring Tool Suite

Version: 3.9.1.RELEASE
Build Id: 201710111105
Platform: Eclipse Oxygen.1a (4.7.1a) 

I tried to use spotBugs to analyze java code using bugs files exclusion but that doesn't work like findBugs plugin. 
I have read spotBugs documentation but unfortunately, that did not help me.
Has this feature been kept in spotBugs ?

**Comment by KengoTODA** [comment]
Yes 3.1 keeps this feature implemented by FindBugs 3.0.
Consider to provide minimal and enough code to reproduce, then someone may help you.

**Comment by ASNOUN** [comment]
Thank you
Using command line, when I execute this line
`java -jar spotbugs.jar -textui`
All options I can use are displayed, especially '-excludeBugs <baseline bugs>'
But when I execute this line 
`java -jar spotbugs.jar -project project.fbp -excludeBugs project_1.xml`
I have this error 
`java.lang.IllegalArgumentException: Unknown option: -excludeBugs
        at edu.umd.cs.findbugs.config.CommandLine.parse(CommandLine.java:333)
        at edu.umd.cs.findbugs.config.CommandLine.parse(CommandLine.java:307)
        at edu.umd.cs.findbugs.config.CommandLine.parse(CommandLine.java:270)
        at edu.umd.cs.findbugs.gui2.Driver.main(Driver.java:64)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at edu.umd.cs.findbugs.LaunchAppropriateUI.launch(LaunchAppropriateUI.java:114)
        at edu.umd.cs.findbugs.LaunchAppropriateUI.main(LaunchAppropriateUI.java:198)
edu.umd.cs.findbugs.gui2.Driver [options] [project or analysis results file]
Options:
  General FindBugs options:
    -project <project>                  analyze given project
    -home <home directory>              specify SpotBugs home directory
    -pluginList <jar1[;jar2...]>        specify list of plugin Jar files to load
    -effort[:min|less|default|more|max] set analysis effort level
    -adjustExperimental                 lower priority of experimental Bug Patterns
    -workHard                           ensure analysis effort is at least 'default'
    -conserveSpace                      same as -effort:min (for backward compatibility)
    -f <font size>                      set font size
    -clear                              clear saved GUI settings and exit
    -priority <thread priority>         set analysis thread priority
    -loadBugs <saved analysis results>  load bugs from saved analysis results
    -d                                  disable docking
    --nodock                            disable docking
    -look[:plastic|gtk|native]          set UI look and feel`

An idea ? tks

**Comment by KengoTODA** [comment]
FindBugs/SpotBugs provides several interfaces, and

> java -jar spotbugs.jar -textui

This uses CLI, and

> java -jar spotbugs.jar -project project.fbp -excludeBugs project_1.xml

This uses GUI. GUI doesn't support `-excludeBugs` option, which is CUI original option. To check options supported by GUI, try `java -jar spotbugs.jar -gui -help`.


Note that the document about command line parameter is here: http://spotbugs.readthedocs.io/en/latest/running.html#command-line-options

**Comment by ASNOUN** [comment]
Thank you for your replay.
I don't understand, which command can I use to excudes file bugs xml? 
 Why I can not do this using eclipse ?

**Comment by KengoTODA** [comment]
> which command can I use to excudes file bugs xml?

No option we have. Check `java -jar spotbugs.jar -gui -help`.

> Why I can not do this using eclipse ?

Simply speaking, nobody wanted it and nobody implemented it.
For now we need to add filter manually from menu bar in GUI window.

**Comment by KengoTODA** [comment]
BTW about how many user interface spotbugs provides, please check official document at here:

http://spotbugs.readthedocs.io/en/stable/running.html#choosing-the-user-interface

Your commands uses different user interface, then each of them accepts different option.
This is what confuses you.

**Comment by JuditKnoll** [comment]
As far as I can see, this issue got answered and resolved.
