### ISSUE TITLE
NET::ERR_CERT_AUTHORITY_INVALID from spotbugs.readthedocs.io

### ISSUE THREAD

**Issue by littleaj** [spotbugs/spotbugs.github.io#38]
The documentation site, https://spotbugs.readthedocs.io/, is throwing a `NET::ERR_CERT_AUTHORITY_INVALID` error:

**Cert Details**
Subject: ssl403572.cloudflaressl.com
Issuer: COMODO ECC Domain Validation Secure Server CA 2
Expires on: Nov 26, 2020
Current date: Jul 10, 2020

This could be an issue with readthedocs.io or cloudflare, because three out of the six featured projects on the readthedocs.io homepage had the same error, surprisingly with the same certificate.

Chrome will not let you proceed with this cert error, but Edge will.

Hopefully this is something you can fix on your end.

**Comment by KengoTODA** [comment]
Fixed
